# Site settings
title: 'Research UAV'
email: contact@reserachuav.com
description: "Research UAV - Building the Future with Drones"
keywords: "Research UAV, Drones, Machine Learning, Future"
baseurl: ""
url: "https://reserachuav.com"

# Build settings
markdown: kramdown

source: .
destination: ./_site
paginate: 5
paginate_path: "blog/page:num"

permalink: /:title/

sass:
  sass_dir: assets/sass
  style: :compressed
