# Site settings
title: 'Research UAV'
email: contact@researchuav.com
description: "Research UAV - Building the Future with Drones"
keywords: "Research UAV, Drones, Machine Learning, Future"
baseurl: "/website"
url: "https://6g-integration-3-uc3m.github.io"

# Build settings
markdown: kramdown

source: .
destination: ./_site
paginate: 5
paginate_path: "blog/page:num"

permalink: /:title/

sass:
  sass_dir: assets/sass
  style: :compressed
